### ISSUE TITLE
.jshintrc

### ISSUE THREAD

**Issue by tomwayson** [gavinr/wab-es6-example-widget#3]
There are a lot of probs w/ the current .jshintrc for es6 code. At the very least it needs `esnext: true`, `esversion: 6`, and to remove `es5: false`.

Prob best to get a better default .jshintrc that is targeted to es6

**Comment by gavinr** [comment]
Agreed this is currently an issue. The current version is directly what comes from https://github.com/Esri/generator-esri-appbuilder-js. We can make those few changes here, and then maybe make broader changes back in the `generator-esri-appbuilder-js` repo
